name: Deploy React/Next.js App to GitHub Pages

on:
  push:
    branches:
      - version_two

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the appropriate Node.js version

      - name: Install dependencies
        working-directory: ./frontend  # Install dependencies from the frontend directory
        run: npm install

      - name: Build the project
        working-directory: ./frontend  # Build the project from the frontend directory
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/out  # Adjust to where the build output is stored (use 'out' if Next.js)
